name: Publish to Modrinth

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Datapack/Mod ZIP & JAR
        run: |
          # Build ZIP
          zip -r "cobblemon-rlm-${{ github.event.release.tag_name }}.zip" assets data META-INF fabric.mod.json pack.mcmeta cobblemon_rlm_pack.png README.md
          
          # Build JAR with a tiny difference to change the file hash
          echo "mod_version" > .is_mod
          zip -r "cobblemon-rlm-${{ github.event.release.tag_name }}.jar" assets data META-INF fabric.mod.json pack.mcmeta cobblemon_rlm_pack.png README.md .is_mod

      - name: Publish JAR to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: GC58bFHM
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: "cobblemon-rlm-${{ github.event.release.tag_name }}.jar"
          name: ${{ github.event.release.name }}
          version: "${{ github.event.release.tag_name }}-jar"
          changelog: ${{ github.event.release.body }}
          version-type: release
          game-version-filter: any
          loaders: |
            fabric
            neoforge
          dependencies: |
            MdwFAVRL(required)

      - name: Wait before publishing ZIP
        run: sleep 15

      - name: Publish ZIP to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: GC58bFHM
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: "cobblemon-rlm-${{ github.event.release.tag_name }}.zip"
          name: ${{ github.event.release.name }}
          version: "${{ github.event.release.tag_name }}-zip"
          changelog: ${{ github.event.release.body }}
          version-type: release
          game-version-filter: any
          loaders: |
            datapack
          dependencies: |
            MdwFAVRL(required)